version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes-backend
    image: faraaz2005/notes-backend:latest 
    ports:
      - "5000:5000"
    # env_file:
    #   - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
      VITE_API_URL: "https://notes-backend-c4zt.onrender.com"
    container_name: notes-frontend
    image: faraaz2005/notes-frontend:latest
    ports:
      - "3000:80"
    # env_file:
    #   - ./frontend/.env
    
    restart: unless-stopped

