name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 25.2.0

    - name: Install backend dependencies and run tests
    
      run: |
        cd backend
        npm ci
        npm test -- --watchAll=false
      env:
        NODE_ENV: test
        MONGODB_TEST_URI: ${{ secrets.MONGODB_TEST_URI }}


    - name: Log in to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image using compose
      run: docker compose -f docker-compose.yml build

    - name: Push Docker images
      run: docker compose -f docker-compose.yml push


    - name: Trigger Render backend deploy
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}

    - name: Trigger Render frontend deploy
      run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}

      
